### ISSUE TITLE
Bug in removeTestStorageSnapshot.pl

### ISSUE THREAD

**Issue by steve-h-hart** [Azure/hana-large-instances-self-service-scripts#16]
"my" variable $filename masks earlier declaration in same scope at /usr/sap/HR1/HDB10/exe/removeTestStorageSnapshot.pl line 55.
"my" variable $sshCmd masks earlier declaration in same scope at /usr/sap/HR1/HDB10/exe/removeTestStorageSnapshot.pl line 56.
Global symbol "$LOG_CRIT" requires explicit package name at /usr/sap/HR1/HDB10/exe/removeTestStorageSnapshot.pl line 703.

Issues resolved by deleting lines 55 and 56
  _my $filename = "HANABackupCustomerDetails.txt";_
  _my $sshCmd = '/usr/bin/ssh';_
and adding line
  _my $LOG_CRIT=3;_

**Comment by Phil-Jensen** [comment]
Thanks.  Easy fixes.  Have updated removeTestStorageSnapshot.pl as per bug report.
