### ISSUE TITLE
Incessant growth of one of the file systems

### ISSUE THREAD

**Issue by westerj** [Azure/hana-large-instances-self-service-scripts#19]
Hi. we have several file systems at azure under a database. the snapshots to netapp work fine, but the file system grows to fill it without (over a week) an idea why.   Also the check point versions (.0 -> .48) leave multiples sometimes (ex: multiple .8 versions).

**Comment by Phil-Jensen** [comment]
Hello, Thanks for contacting us about behaviour you are observing with snapshots.  The best way to progress this would be to submit a support ticket through your company's standard Microsoft support channel.

Thanks

**Comment by westerj** [comment]
Hi Phil,

Looks like the large snapshot issue is tied to the 'full/incr' hana
backups.

That's good.

Working to get those lumps out of the logbackup file system.

What do you think about putting scripts in /usr/local/hli/ ?

Can't see reason to park them inside /hana/shared/BWP/BWP/foo/  aside from
cosmetics?

Do you locate the txt config file from HANA env variables, or... in same
dir as *.pl?

Finally got the ear of the hana guy to take ownership of the cron timings.

Progress in multitasking world... aka.. everything goes slow!!

**Comment by Phil-Jensen** [comment]
Hi, response to your questions as follows...

_1. What do you think about putting scripts in /usr/local/hli/?_
This would be ok, but would be a "non-standard" setup.  The next release (due any day) actually installs them into a non-root users $HOME/bin directory.  One of the reasons is it makes it easy to uninstall (e.g. userdel -r -f <user>).
_2. Can't see reason to park them inside /hana/shared/BWP/BWP/foo/ aside from cosmetics?_
One of the reasons they are in the directory specified today is a call being made to the hdbsql command, which needs to be in the directory the command is run from.  This dependency is removed for v4.0.
_3. Do you locate the txt config file from HANA env variables, or... in same dir as *.pl?_
The config file is expected to be in the same directory as the snapshot commands.

Hope this information helps.

**Comment by westerj** [comment]
Thanks for the update...

Dont think we should run any scripts from /home... rather /opt/ or
/usr/local/bin/
DO LOVE the idea of running as non root though.
What env Variables are inherited or need to be set to find HANA load points?

Ex: $JAVA_HOME or $ORA_TMP

$.02.


*# Make the best of your time and facilities #*

**Comment by Phil-Jensen** [comment]
Of course, system administrators do have various preferences. :)  Thus the installer provides flexibility for the snapshot commands to be put in any location by an experienced administrator, but this has not been tested to be supported by Microsoft.  The installer, by default, will create a non-root user and put the commands and configuration files in their $HOME/bin directory.
